export const books = [
    { id: 1, title: "Atomic Habits", category: "Self Help", publishedYear: 2018, available: true },
    { id: 2, title: "Clean Code", category: "Programming", publishedYear: 2008, available: true },
    { id: 3, title: "The Alchemist", category: "Fiction", publishedYear: 1988, available: false },
    { id: 4, title: "Think and Grow Rich", category: "Motivation", publishedYear: 1937, available: true },
    { id: 5, title: "The Pragmatic Programmer", category: "Programming", publishedYear: 1999, available: true },
    { id: 6, title: "Deep Work", category: "Productivity", publishedYear: 2016, available: true },
    { id: 7, title: "Rich Dad Poor Dad", category: "Finance", publishedYear: 1997, available: false },
    { id: 8, title: "Zero to One", category: "Business", publishedYear: 2014, available: true },
    { id: 9, title: "The Lean Startup", category: "Business", publishedYear: 2011, available: true },
    { id: 10, title: "Sapiens", category: "History", publishedYear: 2011, available: false },
    { id: 11, title: "The Power of Habit", category: "Self Help", publishedYear: 2012, available: true },
    { id: 12, title: "Eloquent JavaScript", category: "Programming", publishedYear: 2018, available: true },
    { id: 13, title: "You Don't Know JS", category: "Programming", publishedYear: 2015, available: true },
    { id: 14, title: "The Psychology of Money", category: "Finance", publishedYear: 2020, available: true },
    { id: 15, title: "Ikigai", category: "Self Help", publishedYear: 2016, available: false },
    { id: 16, title: "The Subtle Art of Not Giving a F*ck", category: "Self Help", publishedYear: 2016, available: true },
    { id: 17, title: "Can't Hurt Me", category: "Motivation", publishedYear: 2018, available: true },
    { id: 18, title: "Start With Why", category: "Business", publishedYear: 2009, available: true },
    { id: 19, title: "The 7 Habits of Highly Effective People", category: "Self Help", publishedYear: 1989, available: true },
    { id: 20, title: "Rework", category: "Business", publishedYear: 2010, available: false },
    { id: 21, title: "Head First Java", category: "Programming", publishedYear: 2005, available: true },
    { id: 22, title: "Design Patterns", category: "Programming", publishedYear: 1994, available: true },
    { id: 23, title: "Refactoring", category: "Programming", publishedYear: 1999, available: false },
    { id: 24, title: "The Clean Coder", category: "Programming", publishedYear: 2011, available: true },
    { id: 25, title: "Hooked", category: "Business", publishedYear: 2014, available: true },
    { id: 26, title: "Thinking, Fast and Slow", category: "Psychology", publishedYear: 2011, available: true },
    { id: 27, title: "Man's Search for Meaning", category: "Philosophy", publishedYear: 1946, available: true },
    { id: 28, title: "The Monk Who Sold His Ferrari", category: "Self Help", publishedYear: 1997, available: false },
    { id: 29, title: "Make Time", category: "Productivity", publishedYear: 2018, available: true },
    { id: 30, title: "Digital Minimalism", category: "Productivity", publishedYear: 2019, available: true },
    { id: 31, title: "The Great Gatsby", category: "Fiction", publishedYear: 1925, available: true },
    { id: 32, title: "To Kill a Mockingbird", category: "Fiction", publishedYear: 1960, available: false },
    { id: 33, title: "1984", category: "Fiction", publishedYear: 1949, available: true },
    { id: 34, title: "Animal Farm", category: "Fiction", publishedYear: 1945, available: true },
    { id: 35, title: "The Hobbit", category: "Fantasy", publishedYear: 1937, available: true },
    { id: 36, title: "Harry Potter and the Philosopher's Stone", category: "Fantasy", publishedYear: 1997, available: false },
    { id: 37, title: "The Lord of the Rings", category: "Fantasy", publishedYear: 1954, available: true },
    { id: 38, title: "The Da Vinci Code", category: "Thriller", publishedYear: 2003, available: true },
    { id: 39, title: "Angels & Demons", category: "Thriller", publishedYear: 2000, available: true },
    { id: 40, title: "Inferno", category: "Thriller", publishedYear: 2013, available: false },
    { id: 41, title: "Steve Jobs", category: "Biography", publishedYear: 2011, available: true },
    { id: 42, title: "Elon Musk", category: "Biography", publishedYear: 2023, available: true },
    { id: 43, title: "The Diary of a Young Girl", category: "Biography", publishedYear: 1947, available: true },
    { id: 44, title: "Educated", category: "Biography", publishedYear: 2018, available: false },
    { id: 45, title: "A Brief History of Time", category: "Science", publishedYear: 1988, available: true },
    { id: 46, title: "The Selfish Gene", category: "Science", publishedYear: 1976, available: true },
    { id: 47, title: "Cosmos", category: "Science", publishedYear: 1980, available: true },
    { id: 48, title: "The Art of War", category: "Strategy", publishedYear: -500, available: true },
    { id: 49, title: "Meditations", category: "Philosophy", publishedYear: 180, available: false },
    { id: 50, title: "The Prince", category: "Politics", publishedYear: 1532, available: true }
];

export const authors = [
    { id: 1, name: "James Clear", country: "USA" },
    { id: 2, name: "Robert C. Martin", country: "USA" },
    { id: 3, name: "Paulo Coelho", country: "Brazil" },
    { id: 4, name: "Stephen King", country: "USA" },
    { id: 5, name: "J.K. Rowling", country: "United Kingdom" },
    { id: 6, name: "George R.R. Martin", country: "USA" },
    { id: 7, name: "Yuval Noah Harari", country: "Israel" },
    { id: 8, name: "Robin Sharma", country: "Canada" },
    { id: 9, name: "Napoleon Hill", country: "USA" },
    { id: 10, name: "Dale Carnegie", country: "USA" },
    { id: 11, name: "Mark Manson", country: "USA" },
    { id: 12, name: "Simon Sinek", country: "United Kingdom" },
    { id: 13, name: "Eric Ries", country: "USA" },
    { id: 14, name: "Cal Newport", country: "USA" },
    { id: 15, name: "Daniel Kahneman", country: "Israel" },
    { id: 16, name: "Seth Godin", country: "USA" },
    { id: 17, name: "Tim Ferriss", country: "USA" },
    { id: 18, name: "Malcolm Gladwell", country: "Canada" },
    { id: 19, name: "Tony Robbins", country: "USA" },
    { id: 20, name: "Ryan Holiday", country: "USA" },
    { id: 21, name: "Harper Lee", country: "USA" },
    { id: 22, name: "Jane Austen", country: "United Kingdom" },
    { id: 23, name: "Charles Dickens", country: "United Kingdom" },
    { id: 24, name: "Ernest Hemingway", country: "USA" },
    { id: 25, name: "Leo Tolstoy", country: "Russia" },
    { id: 26, name: "Fyodor Dostoevsky", country: "Russia" },
    { id: 27, name: "George Orwell", country: "United Kingdom" },
    { id: 28, name: "J.R.R. Tolkien", country: "United Kingdom" },
    { id: 29, name: "Agatha Christie", country: "United Kingdom" },
    { id: 30, name: "Arthur Conan Doyle", country: "United Kingdom" },
    { id: 31, name: "Dan Brown", country: "USA" },
    { id: 32, name: "John Grisham", country: "USA" },
    { id: 33, name: "Khaled Hosseini", country: "Afghanistan" },
    { id: 34, name: "Mitch Albom", country: "USA" },
    { id: 35, name: "Rupi Kaur", country: "Canada" },
    { id: 36, name: "Sudha Murty", country: "India" },
    { id: 37, name: "Chetan Bhagat", country: "India" },
    { id: 38, name: "Amish Tripathi", country: "India" },
    { id: 39, name: "Ruskin Bond", country: "India" },
    { id: 40, name: "Arundhati Roy", country: "India" },
    { id: 41, name: "R.K. Narayan", country: "India" },
    { id: 42, name: "Devdutt Pattanaik", country: "India" },
    { id: 43, name: "Shashi Tharoor", country: "India" },
    { id: 44, name: "Gaur Gopal Das", country: "India" },
    { id: 45, name: "Deepak Chopra", country: "India" },
    { id: 46, name: "Walter Isaacson", country: "USA" },
    { id: 47, name: "Adam Grant", country: "USA" },
    { id: 48, name: "Angela Duckworth", country: "USA" },
    { id: 49, name: "Brené Brown", country: "USA" },
    { id: 50, name: "David Goggins", country: "USA" }
];

export const users = [
    {
        id: 1,
        email: "noorulla@gmail.com",
        // password: "Noor@6199"
        password: "$2b$10$IdlGnhJMsisdJ5eJN3sO9OPizUHa6ZGMUjByIXxx9aAIGr9w4DuDK",
        token: "bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJub29ydWxsYUBnbWFpbC5jb20iLCJpYXQiOjE3ODE4MDA3MjQsImV4cCI6MTc4MTgwNDMyNH0.jltSKwNZRS3f5lOx3vSAQCaT2hlGDKg_5WI5agNkEKc"
    },
    {
        id: 2,
        email: "nowsathali@gmail.com",
        password: "Nowsath@6199"
    }
]